project:
  type: website

website:
  title: "Alabama-Income"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: source.qmd
        text: Source
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



